function getTGx(cos){
  let tgx = {'cos': 0, 'tg': 0, 'ctg': 0};
  if(!(parseFloat(cos) && parseFloat(cos) > 0)) return tgx;
  tgx.cos = cos;
  tgx.tg = Math.pow(Math.pow(cos, -2) -1 , 0.5).toFixed(4);
  tgx.ctg = Math.pow(tgx.tg, -1).toFixed(4);
  return tgx;
}
const g = Math.pow(3, 0.5);
function tg(c) {
  return parseFloat(getTGx(c).tg);
}
function ctg(c){
  return parseFloat(getTGx(c).ctg);
}
function isNull(c){
  return null;
}
const GX = [[{'ABC_IaIbIc_first_true_second_true_third_true'		:(c)=>1},
  {'ABC_IaIbIc_first_true_second_true_third_false'	:	(c)=>3},
  {'ABC_IaIbIc_first_true_second_false_third_true'	:	(c)=>3},
  {'ABC_IaIbIc_first_true_second_false_third_false'	:	(c)=>-3},
  {'ABC_IaIbIc_first_false_second_true_third_true'	:	(c)=>3},
  {'ABC_IaIbIc_first_false_second_true_third_false'	:	(c)=>-3},
  {'ABC_IaIbIc_first_false_second_false_third_true'	:	(c)=>-3},
  {'ABC_IaIbIc_first_false_second_false_third_false':	(c)=>-1},
  {'ABC_IbIcIa_first_true_second_true_third_true'		:(c)=>-2/(1+g*tg(c))},
  {'ABC_IbIcIa_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'ABC_IbIcIa_first_false_second_false_third_false':	(c)=>2/(1+g*tg(c))},
  {'ABC_IcIaIb_first_true_second_true_third_true'		:(c)=>-2/(1-g*tg(c))},
  {'ABC_IcIaIb_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'ABC_IcIaIb_first_false_second_false_third_false':	(c)=>	2/(1-g*tg(c))},
  {'ABC_IaIcIb_first_true_second_true_third_true'		: isNull},
  {'ABC_IaIcIb_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'ABC_IaIcIb_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'ABC_IaIcIb_first_true_second_false_third_false'	:	(c)=>1.5},
  {'ABC_IaIcIb_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'ABC_IaIcIb_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'ABC_IaIcIb_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'ABC_IaIcIb_first_false_second_false_third_false':		isNull},
  {'ABC_IbIaIc_first_true_second_true_third_true'		:isNull},
  {'ABC_IbIaIc_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'ABC_IbIaIc_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'ABC_IbIaIc_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'ABC_IbIaIc_first_false_second_true_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'ABC_IbIaIc_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'ABC_IbIaIc_first_false_second_false_third_true'	:	(c)=>1.5},
  {'ABC_IbIaIc_first_false_second_false_third_false':		isNull},
  {'ABC_IcIbIa_first_true_second_true_third_true'		:isNull},
  {'ABC_IcIbIa_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'ABC_IcIbIa_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'ABC_IcIbIa_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'ABC_IcIbIa_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'ABC_IcIbIa_first_false_second_true_third_false'	:	(c)=>1.5},
  {'ABC_IcIbIa_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'ABC_IcIbIa_first_false_second_false_third_false':		isNull},
  {'BCA_IaIbIc_first_true_second_true_third_true'		:(c)=>-2/(1-g*tg(c))},
  {'BCA_IaIbIc_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'BCA_IaIbIc_first_false_second_false_third_false':	(c)=>2/(1-g*tg(c))},
  {'BCA_IbIcIa_first_true_second_true_third_true'		:(c)=>1},
  {'BCA_IbIcIa_first_true_second_true_third_false'	:	(c)=>3},
  {'BCA_IbIcIa_first_true_second_false_third_true'	:	(c)=>3},
  {'BCA_IbIcIa_first_true_second_false_third_false'	:	(c)=>-3},
  {'BCA_IbIcIa_first_false_second_true_third_true'	:	(c)=>3},
  {'BCA_IbIcIa_first_false_second_true_third_false'	:	(c)=>-3},
  {'BCA_IbIcIa_first_false_second_false_third_true'	:	(c)=>-3},
  {'BCA_IbIcIa_first_false_second_false_third_false'	:	(c)=>-1},
  {'BCA_IcIaIb_first_true_second_true_third_true'	:	(c)=>-2/(1+g*tg(c))},
  {'BCA_IcIaIb_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'BCA_IcIaIb_first_false_second_false_third_false'	:	(c)=>2/(1+g*tg(c))},
  {'BCA_IaIcIb_first_true_second_true_third_true'	:	isNull},
  {'BCA_IaIcIb_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'BCA_IaIcIb_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'BCA_IaIcIb_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'BCA_IaIcIb_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'BCA_IaIcIb_first_false_second_true_third_false'	:	(c)=>1.5},
  {'BCA_IaIcIb_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'BCA_IaIcIb_first_false_second_false_third_false'	:	isNull},
  {'BCA_IbIaIc_first_true_second_true_third_true'	:	isNull},
  {'BCA_IbIaIc_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'BCA_IbIaIc_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'BCA_IbIaIc_first_true_second_false_third_false'	:	(c)=>1.5},
  {'BCA_IbIaIc_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'BCA_IbIaIc_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'BCA_IbIaIc_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'BCA_IbIaIc_first_false_second_false_third_false'	:	isNull},
  {'BCA_IcIbIa_first_true_second_true_third_true'	:	isNull},
  {'BCA_IcIbIa_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'BCA_IcIbIa_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'BCA_IcIbIa_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'BCA_IcIbIa_first_false_second_true_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'BCA_IcIbIa_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'BCA_IcIbIa_first_false_second_false_third_true'		:(c)=>1.5},
  {'BCA_IcIbIa_first_false_second_false_third_false'	:	isNull},
  {'CAB_IaIbIc_first_true_second_true_third_true'	:	(c)=>-2/(1+g*tg(c))},
  {'CAB_IaIbIc_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'CAB_IaIbIc_first_false_second_false_third_false'	:	(c)=>2/(1+g*tg(c))},
  {'CAB_IbIcIa_first_true_second_true_third_true'	:	(c)=>-2/(1-g*tg(c))},
  {'CAB_IbIcIa_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'CAB_IbIcIa_first_false_second_false_third_false'	:	(c)=>2/(1-g*tg(c))},
  {'CAB_IcIaIb_first_true_second_true_third_true'	:	(c)=>1},
  {'CAB_IcIaIb_first_true_second_true_third_false'	:	(c)=>3},
  {'CAB_IcIaIb_first_true_second_false_third_true'	:	(c)=>3},
  {'CAB_IcIaIb_first_true_second_false_third_false'	:	(c)=>-3},
  {'CAB_IcIaIb_first_false_second_true_third_true'	:	(c)=>3},
  {'CAB_IcIaIb_first_false_second_true_third_false'	:	(c)=>-3},
  {'CAB_IcIaIb_first_false_second_false_third_true'	:	(c)=>-3},
  {'CAB_IcIaIb_first_false_second_false_third_false'	:	(c)=>-1},
  {'CAB_IaIcIb_first_true_second_true_third_true'	:	isNull},
  {'CAB_IaIcIb_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'CAB_IaIcIb_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'CAB_IaIcIb_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'CAB_IaIcIb_first_false_second_true_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'CAB_IaIcIb_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'CAB_IaIcIb_first_false_second_false_third_true'	:	(c)=>1.5},
  {'CAB_IaIcIb_first_false_second_false_third_false'	:	isNull},
  {'CAB_IbIaIc_first_true_second_true_third_true'	:	isNull},
  {'CAB_IbIaIc_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'CAB_IbIaIc_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'CAB_IbIaIc_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'CAB_IbIaIc_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'CAB_IbIaIc_first_false_second_true_third_false'	:	(c)=>1.5},
  {'CAB_IbIaIc_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'CAB_IbIaIc_first_false_second_false_third_false'	:	isNull},
  {'CAB_IcIbIa_first_true_second_true_third_true'	:	isNull},
  {'CAB_IcIbIa_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'CAB_IcIbIa_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'CAB_IcIbIa_first_true_second_false_third_false'	:	(c)=>1.5},
  {'CAB_IcIbIa_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'CAB_IcIbIa_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'CAB_IcIbIa_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'CAB_IcIbIa_first_false_second_false_third_false'	:	isNull},
  {'ACB_IaIbIc_first_true_second_true_third_true'	:	isNull},
  {'ACB_IaIbIc_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'ACB_IaIbIc_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'ACB_IaIbIc_first_true_second_false_third_false'	:	(c)=>1.5},
  {'ACB_IaIbIc_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'ACB_IaIbIc_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'ACB_IaIbIc_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'ACB_IaIbIc_first_false_second_false_third_false'	:	isNull},
  {'ACB_IbIcIa_first_true_second_true_third_true'	:	isNull},
  {'ACB_IbIcIa_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'ACB_IbIcIa_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'ACB_IbIcIa_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'ACB_IbIcIa_first_false_second_true_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'ACB_IbIcIa_first_false_second_true_third_false'	:	(c)=>1.5},
  {'ACB_IbIcIa_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'ACB_IbIcIa_first_false_second_false_third_false'	:	isNull},
  {'ACB_IcIaIb_first_true_second_true_third_true'	:	isNull},
  {'ACB_IcIaIb_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'ACB_IcIaIb_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'ACB_IcIaIb_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'ACB_IcIaIb_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'ACB_IcIaIb_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'ACB_IcIaIb_first_false_second_false_third_true'	:	(c)=>1.5},
  {'ACB_IcIaIb_first_false_second_false_third_false'	:	isNull},
  {'ACB_IaIcIb_first_true_second_true_third_true'	:	(c)=>1},
  {'ACB_IaIcIb_first_true_second_true_third_false'	:	(c)=>3},
  {'ACB_IaIcIb_first_true_second_false_third_true'	:	(c)=>3},
  {'ACB_IaIcIb_first_true_second_false_third_false'	:	(c)=>-3},
  {'ACB_IaIcIb_first_false_second_true_third_true'	:	(c)=>3},
  {'ACB_IaIcIb_first_false_second_true_third_false'	:	(c)=>-3},
  {'ACB_IaIcIb_first_false_second_false_third_true'	:	(c)=>-3},
  {'ACB_IaIcIb_first_false_second_false_third_false'	:	(c)=>-1},
  {'ACB_IbIaIc_first_true_second_true_third_true'	:	(c)=>-2/(1+g*tg(c))},
  {'ACB_IbIaIc_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'ACB_IbIaIc_first_false_second_false_third_false'	: (c)=>	2/(1+g*tg(c))},
  {'ACB_IcIbIa_first_true_second_true_third_true'	:	(c)=>	-2/(1-g*tg(c))},
  {'ACB_IcIbIa_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'ACB_IcIbIa_first_false_second_false_third_false'	:(c)=>2/(1-g*tg(c))},
  {'BAC_IaIbIc_first_true_second_true_third_true'	:	isNull},
  {'BAC_IaIbIc_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'BAC_IaIbIc_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'BAC_IaIbIc_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'BAC_IaIbIc_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'BAC_IaIbIc_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'BAC_IaIbIc_first_false_second_false_third_true'	:	(c)=>1.5},
  {'BAC_IaIbIc_first_false_second_false_third_false'	:	isNull},
  {'BAC_IbIcIa_first_true_second_true_third_true'	:	isNull},
  {'BAC_IbIcIa_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'BAC_IbIcIa_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'BAC_IbIcIa_first_true_second_false_third_false'	:	(c)=>1.5},
  {'BAC_IbIcIa_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'BAC_IbIcIa_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'BAC_IbIcIa_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'BAC_IbIcIa_first_false_second_false_third_false'	:	isNull},
  {'BAC_IcIaIb_first_true_second_true_third_true'	:	isNull},
  {'BAC_IcIaIb_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'BAC_IcIaIb_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'BAC_IcIaIb_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'BAC_IcIaIb_first_false_second_true_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'BAC_IcIaIb_first_false_second_true_third_false'	:	(c)=>1.5},
  {'BAC_IcIaIb_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'BAC_IcIaIb_first_false_second_false_third_false'	:	isNull},
  {'BAC_IaIcIb_first_true_second_true_third_true'	: (c)=>-2/(1-g*tg(c))},
  {'BAC_IaIcIb_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'BAC_IaIcIb_first_false_second_false_third_false'	:	(c)=>2/(1-g*tg(c))},
  {'BAC_IbIaIc_first_true_second_true_third_true'	:	(c)=>1},
  {'BAC_IbIaIc_first_true_second_true_third_false'	:	(c)=>3},
  {'BAC_IbIaIc_first_true_second_false_third_true'	:	(c)=>3},
  {'BAC_IbIaIc_first_true_second_false_third_false'	:	(c)=>-3},
  {'BAC_IbIaIc_first_false_second_true_third_true'	:	(c)=>3},
  {'BAC_IbIaIc_first_false_second_true_third_false'	:	(c)=>-3},
  {'BAC_IbIaIc_first_false_second_false_third_true'	:	(c)=>-3},
  {'BAC_IbIaIc_first_false_second_false_third_false'	:	(c)=>-1},
  {'BAC_IcIbIa_first_true_second_true_third_true'	:	(c)=>-2/(1+g*tg(c))},
  {'BAC_IcIbIa_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'BAC_IcIbIa_first_false_second_false_third_false'	:	(c)=>2/(1+g*tg(c))},
  {'CBA_IaIbIc_first_true_second_true_third_true'	:	isNull},
  {'CBA_IaIbIc_first_true_second_true_third_false'	:	(c)=>3/(1-g*tg(c))},
  {'CBA_IaIbIc_first_true_second_false_third_true'	:	(c)=>-1.5},
  {'CBA_IaIbIc_first_true_second_false_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'CBA_IaIbIc_first_false_second_true_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'CBA_IaIbIc_first_false_second_true_third_false'	:	(c)=>1.5},
  {'CBA_IaIbIc_first_false_second_false_third_true'	:	(c)=>-3/(1-g*tg(c))},
  {'CBA_IaIbIc_first_false_second_false_third_false'	:	isNull},
  {'CBA_IbIcIa_first_true_second_true_third_true'	:	isNull},
  {'CBA_IbIcIa_first_true_second_true_third_false'	:	(c)=>-1.5},
  {'CBA_IbIcIa_first_true_second_false_third_true'	:	(c)=>3/(1+g*tg(c))},
  {'CBA_IbIcIa_first_true_second_false_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'CBA_IbIcIa_first_false_second_true_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'CBA_IbIcIa_first_false_second_true_third_false'	:	(c)=>-3/(1+g*tg(c))},
  {'CBA_IbIcIa_first_false_second_false_third_true'	:	(c)=>1.5},
  {'CBA_IbIcIa_first_false_second_false_third_false'	:	isNull},
  {'CBA_IcIaIb_first_true_second_true_third_true'	:	isNull},
  {'CBA_IcIaIb_first_true_second_true_third_false'	:	(c)=>3/(1+g*tg(c))},
  {'CBA_IcIaIb_first_true_second_false_third_true'	:	(c)=>3/(1-g*tg(c))},
  {'CBA_IcIaIb_first_true_second_false_third_false'	:	(c)=>1.5},
  {'CBA_IcIaIb_first_false_second_true_third_true'	:	(c)=>-1.5},
  {'CBA_IcIaIb_first_false_second_true_third_false'	:	(c)=>-3/(1-g*tg(c))},
  {'CBA_IcIaIb_first_false_second_false_third_true'	:	(c)=>-3/(1+g*tg(c))},
  {'CBA_IcIaIb_first_false_second_false_third_false'	:	isNull},
  {'CBA_IaIcIb_first_true_second_true_third_true'	:	(c)=>-2/(1+g*tg(c))},
  {'CBA_IaIcIb_first_true_second_true_third_false'	:	(c)=>-6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_true_second_false_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_true_second_false_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_false_second_true_third_true'	:	(c)=>-6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_false_second_true_third_false'	:	(c)=>6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_false_second_false_third_true'	:	(c)=>6/(1+g*tg(c))},
  {'CBA_IaIcIb_first_false_second_false_third_false'	: (c)=>	2/(1+g*tg(c))},
  {'CBA_IbIaIc_first_true_second_true_third_true'	:	(c)=>-2/(1-g*tg(c))},
  {'CBA_IbIaIc_first_true_second_true_third_false'	:	(c)=>-6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_true_second_false_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_true_second_false_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_false_second_true_third_true'	:	(c)=>-6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_false_second_true_third_false'	:	(c)=>6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_false_second_false_third_true'	:	(c)=>6/(1-g*tg(c))},
  {'CBA_IbIaIc_first_false_second_false_third_false'	:(c)=>	2/(1-g*tg(c))},
  {'CBA_IcIbIa_first_true_second_true_third_true'	:	(c)=>1},
  {'CBA_IcIbIa_first_true_second_true_third_false'	:	(c)=>3},
  {'CBA_IcIbIa_first_true_second_false_third_true'	:	(c)=>3},
  {'CBA_IcIbIa_first_true_second_false_third_false'	:	(c)=>-3},
  {'CBA_IcIbIa_first_false_second_true_third_true'	:	(c)=>3},
  {'CBA_IcIbIa_first_false_second_true_third_false'	:	(c)=>-3},
  {'CBA_IcIbIa_first_false_second_false_third_true'	:	(c)=>-3},
  {'CBA_IcIbIa_first_false_second_false_third_false'	:	(c)=>-1}],

  [{'A'	:	(c)=>1.5},
    {'B'	:	(c)=>1.5},
    {'C'	:	(c)=>1.5},
    {'AB'	:	(c)=>3},
    {'BC'	:	(c)=>3},
    {'AC'	:	(c)=>3},
    {'ABC'	:	isNull}],

  [{'A'	:	(c)=>1.5},
    {'B'	:	(c)=>1.5},
    {'C'	:	(c)=>1.5},
    {'AB'	:	(c)=>3},
    {'BC'	:	(c)=>3},
    {'AC'	:	(c)=>3},
    {'ABC'	:	isNull}]];

export default GX;
